# Generated by Django 2.0.7 on 2018-10-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstructure',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
