# Generated by Django 2.0.7 on 2018-10-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181002_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintstructure',
            name='date',
            field=models.CharField(default=1, max_length=4000),
            preserve_default=False,
        ),
    ]
