# Generated by Django 2.0.7 on 2018-10-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_complaintstructure_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=3000)),
                ('postdate', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'newsposts',
            },
        ),
    ]
