# Generated by Django 2.0.7 on 2018-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_newspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstructure',
            name='cimage1',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='complaintstructure',
            name='cimage2',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='complaintstructure',
            name='cimage3',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
